import Head from "next/head";
import Link from "next/link";
import { navLists } from "./navLists";
const Header = ({ title }) => {
  return (
    <>
      <Head>
        <title>{title ? title : "Home"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="w-full  border-b border-gray-500 z-30 fixed top-0 bg-gray-900 shadow-lg">
        <div className="max-w-6xl px-4 mx-auto md:px-4 lg:px-12">
          <nav className="flex py-2 items-center justify-between">
            <Link
              href={"/"}
              className="logo font-medium text-xl sm:font-semibold text-yellow-500 sm:text-2xl"
            >
              Gambtech
            </Link>

            <div className="search">
              <form
                action=""
                method="get"
                className=" bg-gray-600 rounded-md w-52 sm:w-72 "
              >
                <input
                  type="search"
                  name=""
                  id=""
                  className="w-full p-2 rounded-md outline-none bg-inherit"
                  placeholder="search ...."
                />
              </form>
            </div>

            <ul className="md:flex space-x-6  hidden ">
              {navLists.map(({ name, path, Icon }, index) => (
                <li key={index}>
                  <Link href={path}>
                    <span className="flex justify-center">
                      {<Icon className="w-6 " />}
                    </span>
                    <span className="text-sm  hidden lg:inline">{name}</span>
                  </Link>
                </li>
              ))}
            </ul>
          </nav>
        </div>
      </header>
    </>
  );
};

export default Header;
